### ISSUE TITLE
Promotion request notifications in-game

### ISSUE THREAD

**Issue by MrRedCrack** [Pieter12345/Styms-Redstone-Server#12]
Same thing with the applications. While it may get annoying if there are too many of them, but it's a good thing to remind staffs to judge them faster, as some of the requests had been sitting there for weeks.

**Comment by Pieter12345** [comment]
Added the "/checkpromos" command that will do this, permission is added to ModJr and higher. There is no scheduled broadcast for this as this can be very annoying when a promotion request has to stay open for a while for some reason.
