### ISSUE TITLE
No join message but leave messages, due to quick connection abort

### ISSUE THREAD

**Issue by Ecconia** [Pieter12345/Styms-Redstone-Server#13]
Issue:
If a player aborts the connection while joining, there is the chance, that the server won't send the join message, but a quit message.

Cause:
Join messages only will be sent, when a player is still connected after the join-event has been fired.

Fix:
Move the code to abort the join code after the join broadcast to prevent the inconsistency from occurring.

Due to:
On server 1.13 update.

**Comment by Pieter12345** [comment]
Fixed by modding CraftBukkit 1.13.1. Will apply on server update to 1.13.1.

**Comment by Pieter12345** [comment]
Fixed with the CraftBukkit 1.13.1 update.
