### ISSUE TITLE
Adding afk reason behind the afk message

### ISSUE THREAD

**Issue by MrRedCrack** [Pieter12345/Styms-Redstone-Server#5]
I have a suggestion for the afk system, when you call somebody like "DrCrack" it only tells players that the player is afk right? 
What about adding the afk reason behind that message the players themselves have put so people can easily know why they are afk, and also people can leave messages like "Call my name when you need me!" or something

**Comment by Pieter12345** [comment]
The afk reason is now shown in the `/isafk <player>` command and also added to the automated broadcast when you say some afk players name.
