### ISSUE TITLE
Have an option to disable teleport requests

### ISSUE THREAD

**Issue by MrRedCrack** [Pieter12345/Styms-Redstone-Server#6]
Title says it all. It gets really annoying when I get a lot of teleport requests from a bunch of learners when I don't really feel the need to have teleport requests enabled for me. :/

**Comment by Ecconia** [comment]
it actually is not that clear, do you want to deny or accept all teleport requests. 
Anyway I intend to sooner or later write such a feature in my teleportation plugin :)

**Comment by Pieter12345** [comment]
This has been implemented under the `Teleport requests` setting in the `/settings` command, where you can choose between `ask`, `accept` and `deny` as response to teleport requests.
